<?php
/**@var Magenest\Promotion\Block\Promotion\CountQty $block*/
?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magenest_Promotion::css/1.css')?>">
<li class="nav item">
    <a href="<?php echo $block->getUrl('promo/notification')?>">My Notification
        <?php if ($block->getCountQty()!=0 && $block->getCountQty() != null):?>
        <span class="dot">
            <span class="qty"><?php echo $block->getCountQty()?></span>
        </span>
        <?php endif;?>
    </a>
</li>